


title: more writing
#email:
description: >- 
  words and maybe numbers
baseurl: "/more-writing" # the subpath of your site, e.g. /blog
url: "https://pwhiddy.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username:
#github_username:  PWhiddy

# Build settings
theme: minima
remote_theme: jekyll/minima

minima:
  skin: dark
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
